CONFIG_INPUT_IQS9151_ROTATE_0=y
CONFIG_INPUT_IQS9151_RESOLUTION_X=2457
CONFIG_INPUT_IQS9151_RESOLUTION_Y=3072
CONFIG_INPUT_IQS9151_ATI_TARGETCOUNT=400
CONFIG_INPUT_IQS9151_DYNAMIC_FILTER_BOTTOM_SPEED=30
CONFIG_INPUT_IQS9151_DYNAMIC_FILTER_TOP_SPEED=511
CONFIG_INPUT_IQS9151_DYNAMIC_FILTER_BOTTOM_BETA=20
CONFIG_INPUT_IQS9151_1F_TAP_ENABLE=y
CONFIG_INPUT_IQS9151_1F_TAP_MAX_MS=250
CONFIG_INPUT_IQS9151_1F_TAP_MOVE=50
CONFIG_INPUT_IQS9151_1F_PRESSHOLD_ENABLE=y
CONFIG_INPUT_IQS9151_1F_TAPDRAG_GAP_MAX_MS=160
CONFIG_INPUT_IQS9151_CURSOR_INERTIA_ENABLE=n
CONFIG_INPUT_IQS9151_CURSOR_INERTIA_DECAY=950
CONFIG_INPUT_IQS9151_CURSOR_INERTIA_RECENT_WINDOW_MS=60
CONFIG_INPUT_IQS9151_CURSOR_INERTIA_STALE_GAP_MS=35
CONFIG_INPUT_IQS9151_CURSOR_INERTIA_MIN_SAMPLES=2
CONFIG_INPUT_IQS9151_CURSOR_INERTIA_MIN_AVG_SPEED=10
CONFIG_INPUT_IQS9151_2F_TAP_ENABLE=y
CONFIG_INPUT_IQS9151_2F_TAP_MAX_MS=250
CONFIG_INPUT_IQS9151_2F_TAP_MOVE=50
CONFIG_INPUT_IQS9151_2F_PRESSHOLD_ENABLE=y
CONFIG_INPUT_IQS9151_2F_TAPDRAG_GAP_MAX_MS=200
CONFIG_INPUT_IQS9151_SCROLL_Y_ENABLE=y
CONFIG_INPUT_IQS9151_SCROLL_X_ENABLE=y
CONFIG_INPUT_IQS9151_2F_SCROLL_START_MOVE=50
CONFIG_INPUT_IQS9151_SCROLL_INERTIA_ENABLE=y
CONFIG_INPUT_IQS9151_SCROLL_INERTIA_DECAY=980
CONFIG_INPUT_IQS9151_SCROLL_INERTIA_RECENT_WINDOW_MS=60
CONFIG_INPUT_IQS9151_SCROLL_INERTIA_STALE_GAP_MS=35
CONFIG_INPUT_IQS9151_SCROLL_INERTIA_MIN_SAMPLES=1
CONFIG_INPUT_IQS9151_SCROLL_INERTIA_MIN_AVG_SPEED=4
CONFIG_INPUT_IQS9151_2F_PINCH_ENABLE=y
CONFIG_INPUT_IQS9151_2F_PINCH_START_DISTANCE=100
CONFIG_INPUT_IQS9151_2F_PINCH_WHEEL_GAIN_X10=40
CONFIG_INPUT_IQS9151_3F_TAP_ENABLE=y
CONFIG_INPUT_IQS9151_3F_TAP_MAX_MS=200
CONFIG_INPUT_IQS9151_3F_TAP_MOVE=35
CONFIG_INPUT_IQS9151_3F_PRESSHOLD_ENABLE=y
CONFIG_INPUT_IQS9151_3F_TAPDRAG_GAP_MAX_MS=200
CONFIG_INPUT_IQS9151_3F_SWIPE_THRESHOLD=200
